apiVersion: v1
kind: Namespace
metadata:
  name: wgu-demo
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: wgu-demo-frontend
  labels:
    istio.io/dataplane-mode: ambient
